version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hom-api
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_DB: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine
    container_name: hom-db
    restart: always
    environment:
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
