### Test
GET http://localhost:3003/test

### Add new word
POST http://localhost:3003/api/vocabulary/1
Content-Type: application/json

{
    "text": "test",
    "language": "en",
    "userId": "{{userId}}"
}

###
